# This is an example Docker Compose file to build from (or can be copied as-is). Ensure `DailyWirePodcastProxy.ini` is local to the compose file, or adjust the volume mapping accordingly

version: '3'
services:
  DailyWire-Podcast-Proxy:
    container_name: dailywirepodcastproxy
    image: ghcr.io/kfriede/dailywirepodcastproxy:master
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - 9473:9473
    volumes:
      - ./DailyWirePodcastProxy.ini:/opt/publish/linux-x64/DailyWirePodcastProxy.ini
